from django.db import models

class HkPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.IntegerField()
    CCSDSTYPE = models.IntegerField()
    CCSDSSHF = models.IntegerField()
    CCSDSAPID = models.IntegerField()
    CCSDSSEQFLAGS = models.IntegerField()
    CCSDSSEQCNT = models.IntegerField()
    CCSDSLENGTH = models.IntegerField()
    SHCOARSE = models.BigIntegerField()
    SHFINE = models.BigIntegerField()
    Cmd_ADF_Counts  = models.IntegerField()
    Cmd_RS485_Succ_Counts = models.IntegerField()
    Cmd_RS485_Fail_Counts = models.IntegerField()
    Image_ID = models.IntegerField()
    CLK_Rate = models.IntegerField()
    Command_Loss_Timer = models.BigIntegerField()
    Prev_CMD_Receive = models.IntegerField()
    Latest_CodeWord_RCV = models.IntegerField()
    Reset_Counts = models.IntegerField()
    RTM = models.CharField(max_length=200)
    Acc_X = models.DecimalField(max_digits=20, decimal_places=7)
    Acc_Y = models.DecimalField(max_digits=20, decimal_places=7)
    Acc_Z = models.DecimalField(max_digits=20, decimal_places=7)
    Roll_Rate = models.DecimalField(max_digits=20, decimal_places=14)
    Pitch_Rate = models.DecimalField(max_digits=20, decimal_places=14)
    Yaw_Rate = models.DecimalField(max_digits=20, decimal_places=14)
    IMU_Temp = models.DecimalField(max_digits=20, decimal_places=14)
    CDH_Voltage = models.DecimalField(max_digits=20, decimal_places=14)
    PIS_Voltage = models.DecimalField(max_digits=20, decimal_places=14)
    Other_Voltages = models.CharField(max_length=200)
    CDH_Current = models.DecimalField(max_digits=20, decimal_places=14)
    PIS_Current = models.DecimalField(max_digits=20, decimal_places=14)
    Other_Currents = models.CharField(max_length=200)
    HK_Read_Pointer = models.IntegerField()
    HK_Write_Pointer = models.IntegerField()
    Thermistor_Read_Pointer  = models.IntegerField()
    Thermistor_Write_Pointer  = models.IntegerField()
    Comms_Read_Pointer = models.IntegerField()
    Comms_Write_Pointer = models.IntegerField()
    sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.CharField(max_length=400)
    Fletcher_Code = models.IntegerField()

class GmcPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.IntegerField()
    CCSDSTYPE = models.IntegerField()
    CCSDSSHF = models.IntegerField()
    CCSDSAPID = models.IntegerField()
    CCSDSSEQFLAGS = models.IntegerField()
    CCSDSSEQCNT = models.IntegerField()
    CCSDSLENGTH = models.IntegerField()
    SHCOARSE = models.BigIntegerField()
    SHFINE = models.BigIntegerField()
    Image_ID = models.IntegerField()
    GMC_Radiation_Counts = models.IntegerField()
    GMC_Read_Free_Register = models.IntegerField()
    GMC_Payload_Supply_Voltage =  models.DecimalField(max_digits=20, decimal_places=14)
    GM_Tube_High_Voltage =  models.DecimalField(max_digits=20, decimal_places=14)
    HVDC_IC_Control_Voltage =  models.DecimalField(max_digits=20, decimal_places=14)
    Comparator_Reference_Voltage =  models.DecimalField(max_digits=20, decimal_places=14)
    Other_Channel_Of_ADC = models.CharField(max_length=200) 
    GMC_sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.CharField(max_length=400)
    Fletcher_Code = models.IntegerField()

class CommsPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.IntegerField()
    CCSDSTYPE = models.IntegerField()
    CCSDSSHF = models.IntegerField()
    CCSDSAPID = models.IntegerField()
    CCSDSSEQFLAGS = models.IntegerField()
    CCSDSSEQCNT = models.IntegerField()
    CCSDSLENGTH = models.IntegerField()
    SHCOARSE = models.BigIntegerField()
    SHFINE = models.BigIntegerField()
    Image_ID =models.IntegerField()
    Comms_ADF_CMD_Rx = models.IntegerField()
    Comms_ADF_CMD_Succ = models.IntegerField()
    Comms_ADF_CMD_REJECT = models.IntegerField()
    Comms_ADF_RSSI_CCA = models.DecimalField(max_digits=20, decimal_places=14)
    Comms_ADF_RSSI = models.DecimalField(max_digits=20, decimal_places=14)
    Comms_ADF_Preamble_Pattern = models.IntegerField()
    Comms_ADF_Sync_Word = models.IntegerField()
    Comms_ADF_Freq = models.IntegerField()
    Comms_ADF_Read_REG_ADDR = models.IntegerField()
    Comms_ADF_Read_REG_No_Double_Words = models.IntegerField()
    Comms_ADF_Data = models.CharField(max_length=400)
    Comms_ADF_State = models.IntegerField()
    sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.CharField(max_length=400)
    Fletcher_Code = models.IntegerField()

class TempPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.IntegerField()
    CCSDSTYPE = models.IntegerField()
    CCSDSSHF = models.IntegerField()
    CCSDSAPID = models.IntegerField()
    CCSDSSEQFLAGS = models.IntegerField()
    CCSDSSEQCNT = models.IntegerField()
    CCSDSLENGTH = models.IntegerField()
    SHCOARSE = models.BigIntegerField()
    SHFINE = models.BigIntegerField()
    GMC_Temperature = models.DecimalField(max_digits=20, decimal_places=14)
    PIS_Temperature = models.DecimalField(max_digits=20, decimal_places=14)
    CUB_Temperature = models.DecimalField(max_digits=20, decimal_places=14)
    OBC_Temperature = models.DecimalField(max_digits=20, decimal_places=14)
    Sun_Facing_Connector_Temp = models.DecimalField(max_digits=20, decimal_places=14)
    Sun_Facing_Flat_Temp = models.DecimalField(max_digits=20, decimal_places=14)
    Adjacent_Sun_Facing_Window_Temp = models.DecimalField(max_digits=20, decimal_places=14)
    Base_Plate_Temp = models.DecimalField(max_digits=20, decimal_places=14)
    sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.CharField(max_length=200)
    Fletcher_Code = models.IntegerField()

class InitPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.IntegerField()
    CCSDSTYPE = models.IntegerField()
    CCSDSSHF = models.IntegerField()
    CCSDSAPID = models.IntegerField()
    CCSDSSEQFLAGS = models.IntegerField()
    CCSDSSEQCNT = models.IntegerField()
    CCSDSLENGTH = models.IntegerField()
    SHCOARSE = models.BigIntegerField()
    SHFINE = models.BigIntegerField()
    Image_ID = models.IntegerField()
    status = models.CharField(max_length=200)
    ADF_Init = models.IntegerField()
    config = models.CharField(max_length=200)
    GPS_Time_State_Vector = models.CharField(max_length=400)
    Fletcher_Code = models.IntegerField()

